export const CHANGE_DRAWER_STATUS = "MESSAGE/CHANGE_DRAWER_STATUS";
export const RENEW_MSGWINMODAL_SHOW="MESSAGE/RENEW_MESWINMODAL_SHOW";
export const RECEIVE_MSG_LIST = "MESSAGE/RECEIVE_MSG_LIST"; //message list
export const RECEIVE_MSG = "MESSAGE/RECEIVE_MSG"; // single msg