export const LOG_IN = "HEADER/LOGIN";
export const LOG_OUT = "HEADER/LOGOUT";
export const LOGIN_SET = "HEADER/LOGINSET";
export const RENEW_SEARCH_VAL = "HEADER/RENEWSEARCHVAL";
export const ERROR_MSG = "HEADER/ERROR_MSG";
export const UPDATE_AVATAR = "HEADER/UPDATE_AVATAR";