export const ACCESS_DENIED_MODAL = "POST/ACCESS_DENIED_MODAL";
export const REGISTER_OK = "POST/REGISTER_OK";
export const REGISTER_CANCEL = "POST/REGISTER_CANCEL";
export const POST_ARTICLE = "POST/POST_ARTICLE";
